networks:
  caddy-net:
    external: true

services:
  cloudflared:
    container_name: cloudflared
    hostname: cloudflared
    image: cloudflare/cloudflared:2026.7.3
    restart: unless-stopped
    command: tunnel --no-autoupdate run --credentials-file /home/nonroot/.cloudflared/creds.json ${TUNNEL_ID}
    volumes:
      - ${TUNNEL_CREDS_FILE}:/home/nonroot/.cloudflared/creds.json:ro
    networks:
      - caddy-net
    extends:
      file: docker-compose.base.yml
      service: base
